apply plugin: 'com.android.application'

android {
    namespace 'org.amoradi.syncopoli'
    compileSdkVersion 35

    defaultConfig {
        applicationId "org.amoradi.syncopoli"
        minSdkVersion 19
        targetSdkVersion 35
        versionCode 26
        versionName "v0.7.2"
        vectorDrawables.useSupportLibrary = true

        externalNativeBuild {
            ndkBuild {
                targets 'ssh', 'rsync'
                 arguments 'NDK_LOG=1'
            }
        }

        ndk {
            abiFilters 'armeabi-v7a', 'x86', 'arm64-v8a', 'x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig true
    }

    lintOptions {
        abortOnError false
    }
}

afterEvaluate {
    android.applicationVariants.all { variant ->
        def variantName = variant.name.capitalize()
        def externalNativeBuildTask = tasks.findByName("externalNativeBuild${variantName}")
        def mergeAssetsTask = tasks.findByName("merge${variantName}Assets")

        if (externalNativeBuildTask && mergeAssetsTask) {
            mergeAssetsTask.dependsOn externalNativeBuildTask

            externalNativeBuildTask.doLast {
                def buildType = variant.buildType.name.capitalize()
                def buildDir = rootProject.file("app/build/intermediates/cxx/${buildType}/")

                if (buildDir.exists()) {
                    buildDir.eachDir { dir ->
                        def src = new File(dir, "obj/local")
                        if (src.exists()) {
                            def dst = rootProject.file('app/src/main/assets/')
                            copy {
                                from(src) {
                                    exclude "**/objs"
                                    exclude "**/objs-debug"
                                    exclude "**/*.a"
                                    exclude "**/*.o"
                                    exclude "**/*.d"
                                }

                                into dst

                                eachFile {
                                    println "copying " + it.getPath() + " to assets directory"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

clean {
	delete '.externalNativeBuild'
}

tasks.withType(Test) {
    testLogging {
        exceptionFormat 'full'
        showCauses true
        showExceptions true
        showStackTraces true
        showStandardStreams true
    }
}
		
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
}
